### ISSUE TITLE
Scroll down to load more posts

### ISSUE THREAD

**Issue by sobujbd** [scottopolis/ionic2-wp-api#1]
Sir,
First I want to say thanks for nice project, Defiantly its +1

Second,
How do implement scroll down to load more posts?

**Comment by scottopolis** [comment]
You can use the ion-infinite-scroll tag for that.  You can see an example here:

Template: https://github.com/apppresser/ap3/blob/master/src/pages/post-list/post-list.html#L124

JS: https://github.com/apppresser/ap3/blob/master/src/pages/post-list/post-list.ts#L206
